{% set version = "0.1.3" %}
{% set build = 0 %}

package:
  name: awex
  version: {{ version }}

source:
  #git_url: https://github.com/BoldingBruggeman/awex.git
  url: https://github.com/BoldingBruggeman/awex/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 989e62bb768755e5dbceebba39381f0a8867b3f4c5e35d5dcabac9e420bb32b5

build:
  number: {{ build }}

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - cmake
    - make                                   # [not win]
    - ninja                                  # [win]
    - {{ stdlib("c") }}
    - {{ compiler("c") }}
    - {{ compiler("fortran") }}
  host:
    - python {{ python }}
    - cython
    - pip
    - setuptools
    - numpy
    - libpython                              # [win]
  run:
    - python


test:
  imports:
    - awex

about:
  home: https://github.com/BoldingBruggeman/awex
  summary: 'Python package for calculating air-water exchange of heat and momentum'
  description: |
    The Air-Water EXchange Python package contains algorithms for calculating
    air-water fluxes of sensible/latent heat and momentum from meteorological
    conditions and the surface state of the ocean/lake. Its core is written in
    Fortran for maximum performance. This makes it suitable for calculating
    air-water exchange during simulations with Python-based hydrodynamic models.
  license: GPL-2.0-only
  license_family: GPL
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jornbr
